// Generated by wit-bindgen. DO NOT EDIT.
//
// Shared FFI helpers for wit-bindgen AssemblyScript bindings.
//
// Memory-safety contract: all generated code that takes a raw pointer out of an
// AssemblyScript object (string, Array, Uint8Array, …) does so *only* after
// stashing the source into a named local. AS GC marks named locals as roots, so
// the source object survives any allocation that happens before the wasm import
// call. No explicit __pin / __unpin needed for the generated code paths.
//
// The return-area buffer below is single-instance and therefore NOT re-entrant:
// a host import must not synchronously re-enter through a callback that itself
// uses a multi-value-return import, or the outer call's result will be
// corrupted.

// ---------------------------------------------------------------------------
// abort entry point used via `--use abort=ffi.abort`. Trap directly via wasm
// `unreachable` — staying out of WASI keeps the component import set clean.
// ---------------------------------------------------------------------------

export function abort(
  _msg: string | null,
  _file: string | null,
  _line: i32,
  _col: i32,
): void {
  unreachable();
}

// ---------------------------------------------------------------------------
// cabi_realloc — exported so the host can allocate guest memory.
// ---------------------------------------------------------------------------

export function cabi_realloc(
  ptr: usize,
  _oldSize: usize,
  align: u32,
  newSize: usize,
): usize {
  // AssemblyScript's TLSF allocator hands back 16-byte-aligned blocks, which
  // covers every alignment the canonical ABI asks for today (8 at most). There
  // is no aligned-allocation entry point to fall back on, so assert rather than
  // silently returning a mis-aligned block if that ever stops being true.
  assert(align <= 16);
  if (newSize == 0) {
    if (ptr != 0) heap.free(ptr);
    return 0;
  }
  if (ptr == 0) return heap.alloc(newSize);
  return heap.realloc(ptr, newSize);
}

// ---------------------------------------------------------------------------
// String lift/lower (UTF-16). Zero-copy lower, fresh allocation on lift.
//
// AssemblyScript stores strings as raw UTF-16 code units; the pointer obtained
// via changetype<usize>(s) addresses the first code unit, and s.length is the
// code-unit count which equals canonical-ABI byteLen / 2.
// ---------------------------------------------------------------------------

@inline
export function strLift(ptr: usize, codeUnitLen: usize): string {
  return String.UTF16.decodeUnsafe(ptr, codeUnitLen << 1);
}

// ---------------------------------------------------------------------------
// Numeric list lift helpers — copy out of linear memory into a fresh AS array.
// Numeric list lower helpers — copy AS array contents into a fresh wasm buffer
// allocated via cabi_realloc; the buffer is owned by the receiver.
// ---------------------------------------------------------------------------

// The canonical ABI hands lengths over as u32, but AssemblyScript's typed
// array constructors take i32: a length at or above 2^31 would arrive as a
// negative size. Trap on it instead of constructing a bogus array.
@inline
function checkedLen(len: u32): i32 {
  assert(len <= <u32>i32.MAX_VALUE);
  return <i32>len;
}

export function u8ArrayLift(ptr: usize, len: u32): Uint8Array {
  const out = new Uint8Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, <usize>len);
  return out;
}

export function u8ArrayLower(arr: Uint8Array): usize {
  const len = <usize>arr.length;
  if (len == 0) return 0;
  const buf = heap.alloc(len);
  memory.copy(buf, arr.dataStart, len);
  return buf;
}

export function i8ArrayLift(ptr: usize, len: u32): Int8Array {
  const out = new Int8Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, <usize>len);
  return out;
}

export function i8ArrayLower(arr: Int8Array): usize {
  const len = <usize>arr.length;
  if (len == 0) return 0;
  const buf = heap.alloc(len);
  memory.copy(buf, arr.dataStart, len);
  return buf;
}

export function u16ArrayLift(ptr: usize, len: u32): Uint16Array {
  const out = new Uint16Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 1);
  return out;
}

export function u16ArrayLower(arr: Uint16Array): usize {
  const bytes = (<usize>arr.length) << 1;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function i16ArrayLift(ptr: usize, len: u32): Int16Array {
  const out = new Int16Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 1);
  return out;
}

export function i16ArrayLower(arr: Int16Array): usize {
  const bytes = (<usize>arr.length) << 1;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function u32ArrayLift(ptr: usize, len: u32): Uint32Array {
  const out = new Uint32Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 2);
  return out;
}

export function u32ArrayLower(arr: Uint32Array): usize {
  const bytes = (<usize>arr.length) << 2;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function i32ArrayLift(ptr: usize, len: u32): Int32Array {
  const out = new Int32Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 2);
  return out;
}

export function i32ArrayLower(arr: Int32Array): usize {
  const bytes = (<usize>arr.length) << 2;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function u64ArrayLift(ptr: usize, len: u32): Uint64Array {
  const out = new Uint64Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 3);
  return out;
}

export function u64ArrayLower(arr: Uint64Array): usize {
  const bytes = (<usize>arr.length) << 3;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function i64ArrayLift(ptr: usize, len: u32): Int64Array {
  const out = new Int64Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 3);
  return out;
}

export function i64ArrayLower(arr: Int64Array): usize {
  const bytes = (<usize>arr.length) << 3;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function f32ArrayLift(ptr: usize, len: u32): Float32Array {
  const out = new Float32Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 2);
  return out;
}

export function f32ArrayLower(arr: Float32Array): usize {
  const bytes = (<usize>arr.length) << 2;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

export function f64ArrayLift(ptr: usize, len: u32): Float64Array {
  const out = new Float64Array(checkedLen(len));
  memory.copy(out.dataStart, ptr, (<usize>len) << 3);
  return out;
}

export function f64ArrayLower(arr: Float64Array): usize {
  const bytes = (<usize>arr.length) << 3;
  if (bytes == 0) return 0;
  const buf = heap.alloc(bytes);
  memory.copy(buf, arr.dataStart, bytes);
  return buf;
}

// ---------------------------------------------------------------------------
// char helpers — WIT `char` is a Unicode Scalar Value, lowered as i32.
// ---------------------------------------------------------------------------

@inline export function charFromU32(v: u32): i32 { return <i32>v; }
@inline export function u32FromChar(c: i32): u32 { return <u32>c; }

// ---------------------------------------------------------------------------
// Option<T>. `tag == 0` = none, `tag == 1` = some. Use Option.some(v) /
// Option.none<T>() for clarity. For "none", `value` is a default-constructed T
// (zero for primitives; for class types T, callers must pass an arbitrary
// instance because AS classes can't be left default-uninitialized).
// ---------------------------------------------------------------------------

export class Option<T> {
  constructor(public tag: i32, public value: T) {}
  isSome(): bool { return this.tag == 1; }
  isNone(): bool { return this.tag == 0; }
}

// ---------------------------------------------------------------------------
// Result<O, E>. `tag == 0` = ok, `tag == 1` = err. Both branches need a
// value of the appropriate type; for the inactive branch use a sentinel
// default (zero for primitives, changetype<T>(0) for classes).
// ---------------------------------------------------------------------------

export class Result<O, E> {
  constructor(public tag: i32, public okValue: O, public errValue: E) {}
  isOk(): bool { return this.tag == 0; }
  isErr(): bool { return this.tag == 1; }
}

// ---------------------------------------------------------------------------
// Tuple classes. WIT `tuple<A, B, ...>` lowers to one of these; field access
// uses positional accessors `_0`, `_1`, ....
// ---------------------------------------------------------------------------

export class Tuple1<A> { constructor(public _0: A) {} }
export class Tuple2<A, B> { constructor(public _0: A, public _1: B) {} }
export class Tuple3<A, B, C> { constructor(public _0: A, public _1: B, public _2: C) {} }
export class Tuple4<A, B, C, D> { constructor(public _0: A, public _1: B, public _2: C, public _3: D) {} }
export class Tuple5<A, B, C, D, E> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E) {} }
export class Tuple6<A, B, C, D, E, F> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F) {} }
export class Tuple7<A, B, C, D, E, F, G> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G) {} }
export class Tuple8<A, B, C, D, E, F, G, H> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H) {} }
export class Tuple9<A, B, C, D, E, F, G, H, I> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I) {} }
export class Tuple10<A, B, C, D, E, F, G, H, I, J> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J) {} }
export class Tuple11<A, B, C, D, E, F, G, H, I, J, K> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J, public _10: K) {} }
export class Tuple12<A, B, C, D, E, F, G, H, I, J, K, L> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J, public _10: K, public _11: L) {} }
export class Tuple13<A, B, C, D, E, F, G, H, I, J, K, L, M> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J, public _10: K, public _11: L, public _12: M) {} }
export class Tuple14<A, B, C, D, E, F, G, H, I, J, K, L, M, N> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J, public _10: K, public _11: L, public _12: M, public _13: N) {} }
export class Tuple15<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J, public _10: K, public _11: L, public _12: M, public _13: N, public _14: O) {} }
export class Tuple16<A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> { constructor(public _0: A, public _1: B, public _2: C, public _3: D, public _4: E, public _5: F, public _6: G, public _7: H, public _8: I, public _9: J, public _10: K, public _11: L, public _12: M, public _13: N, public _14: O, public _15: P) {} }
