// Generated by wit-bindgen. DO NOT EDIT.
//
// Async runtime support for wit-bindgen AssemblyScript bindings.
//
// AssemblyScript has no language-level async/await or event loop, so async
// component-model support is an explicit stackless runtime:
// generated export wrappers return callback codes to the host and the host
// drives the wasm `[callback]` export with waitable events.
//
// This file only declares the *shared* pieces: waitable-set wrappers, event
// constants, subtask helpers, and the packing/unpacking of canonical status
// codes. Per-function `task.return` helpers are emitted by the generator.
// Future/stream payload endpoint operations are deliberately not exposed yet.

// ---------------------------------------------------------------------------
// Canonical constants (mirrors the C/Rust/MoonBit runtimes)
// ---------------------------------------------------------------------------

// Subtask status codes returned by async imports.
export const STATUS_STARTING: i32 = 0;
export const STATUS_STARTED: i32 = 1;
export const STATUS_RETURNED: i32 = 2;
export const STATUS_STARTED_CANCELLED: i32 = 3;
export const STATUS_RETURNED_CANCELLED: i32 = 4;

// Waitable (future/stream) result codes.
export const WAITABLE_COMPLETED: i32 = 0;
export const WAITABLE_DROPPED: i32 = 1;
export const WAITABLE_CANCELLED: i32 = 2;

// Callback codes returned by async export wrappers.
export const CALLBACK_CODE_EXIT: i32 = 0;
export const CALLBACK_CODE_YIELD: i32 = 1;

// Event codes delivered to the `[callback]` export.
export const EVENT_NONE: i32 = 0;
export const EVENT_SUBTASK: i32 = 1;
export const EVENT_STREAM_READ: i32 = 2;
export const EVENT_STREAM_WRITE: i32 = 3;
export const EVENT_FUTURE_READ: i32 = 4;
export const EVENT_FUTURE_WRITE: i32 = 5;
export const EVENT_CANCEL: i32 = 6;

// Packing helpers.
//
// A callback code WAIT(set) is `2 | (set << 4)`.
// A subtask status is `state | (handle << 4)`.
// A waitable status is `state | (count << 4)`, or -1 while blocked.

@inline
export function callbackWait(set: i32): i32 {
  return 2 | (set << 4);
}

@inline
export function subtaskState(status: i32): i32 {
  return status & 0xf;
}

@inline
export function subtaskHandle(status: i32): i32 {
  // The packed handle is unsigned; an arithmetic shift would sign-extend a
  // handle at or above 2^27 into a negative value.
  return status >>> 4;
}

@inline
export function waitableState(status: i32): i32 {
  return status & 0xf;
}

@inline
export function waitableCount(status: i32): i32 {
  // Unsigned for the same reason as `subtaskHandle`.
  return status >>> 4;
}

// ---------------------------------------------------------------------------
// Canonical built-in imports shared by every async world.
// ---------------------------------------------------------------------------

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-new]")
declare function __waitable_set_new(): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-drop]")
declare function __waitable_set_drop(set: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-join]")
declare function __waitable_join(waitable: i32, set: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-poll]")
declare function __waitable_set_poll(set: i32, payload: usize): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-wait]")
declare function __waitable_set_wait(set: i32, payload: usize): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[subtask-cancel]")
declare function __subtask_cancel(handle: i32): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[subtask-drop]")
declare function __subtask_drop(handle: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[backpressure-inc]")
declare function __backpressure_inc(): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[backpressure-dec]")
declare function __backpressure_dec(): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("[export]$root", "[task-cancel]")
declare function __task_cancel(): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[context-set-0]")
declare function __context_set_0(value: usize): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[context-get-0]")
declare function __context_get_0(): usize;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[thread-yield]")
declare function __thread_yield(): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[error-context-new-utf8]")
declare function __error_context_new_utf8(ptr: usize, len: usize): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[error-context-drop]")
declare function __error_context_drop(handle: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[error-context-debug-message-utf8]")
declare function __error_context_debug_message_utf8(handle: i32, retptr: usize): void;

// ---------------------------------------------------------------------------
// Waitable-set wrapper
// ---------------------------------------------------------------------------

// Waitable event payload: [waitable, code]. Single-instance buffer; wait/poll
// results must be consumed before the next call, and a nested wait/poll would
// overwrite an outer one's result.
const __WAITABLE_PAYLOAD: usize = changetype<usize>(memory.data(8));

// STACKFUL USE ONLY. `wait()` and `poll()` below block inside the guest. A
// callback-ABI task must never block: it has to return `callbackWait(set)` and
// let the host re-enter through the `[callback]` export. Generated code
// therefore never calls these, and neither should an async export task. They
// exist for guests driving the ABI themselves from a synchronous export.
//
// This class is also managed while tasks are `@unmanaged`, so an instance
// cannot be persisted on a task across a suspension — keep the raw handle from
// `waitableSetNew()` instead.
export class WaitableSet {
  waitable: i32 = 0;
  code: i32 = 0;

  constructor(public handle: i32) {}

  static new(): WaitableSet {
    return new WaitableSet(__waitable_set_new());
  }

  join(waitable: i32): void {
    __waitable_join(waitable, this.handle);
  }

  wait(): i32 {
    store<i32>(__WAITABLE_PAYLOAD, 0);
    store<i32>(__WAITABLE_PAYLOAD + 4, 0);
    const event = __waitable_set_wait(this.handle, __WAITABLE_PAYLOAD);
    this.waitable = load<i32>(__WAITABLE_PAYLOAD);
    this.code = load<i32>(__WAITABLE_PAYLOAD + 4);
    return event;
  }

  poll(): i32 {
    store<i32>(__WAITABLE_PAYLOAD, 0);
    store<i32>(__WAITABLE_PAYLOAD + 4, 0);
    const event = __waitable_set_poll(this.handle, __WAITABLE_PAYLOAD);
    this.waitable = load<i32>(__WAITABLE_PAYLOAD);
    this.code = load<i32>(__WAITABLE_PAYLOAD + 4);
    return event;
  }

  drop(): void {
    __waitable_set_drop(this.handle);
  }
}

// ---------------------------------------------------------------------------
// Subtask / cancellation / context helpers
// ---------------------------------------------------------------------------

export function subtaskCancel(subtask: i32): i32 {
  return __subtask_cancel(subtask);
}

export function subtaskDrop(subtask: i32): void {
  __subtask_drop(subtask);
}

export function waitableJoin(waitable: i32, set: i32): void {
  __waitable_join(waitable, set);
}

export function waitableSetNew(): i32 {
  return __waitable_set_new();
}

export function waitableSetWait(set: i32, payload: usize): i32 {
  return __waitable_set_wait(set, payload);
}

export function waitableSetDrop(set: i32): void {
  __waitable_set_drop(set);
}

export function backpressureInc(): void {
  __backpressure_inc();
}

export function backpressureDec(): void {
  __backpressure_dec();
}

export function taskCancel(): void {
  __task_cancel();
}

// Per-task context slot (context-set/get-0). Generated export wrappers store
// task state here across wait/event boundaries, exactly like the C backend's
// `test_context_set_0`.
export function contextSet(value: usize): void {
  __context_set_0(value);
}

export function contextGet(): usize {
  return __context_get_0();
}

// Returns true when the task was cancelled while suspended at this yield
// point. Discarding the result would make cancellation unobservable here.
export function threadYield(): bool {
  return __thread_yield() != 0;
}

// ---------------------------------------------------------------------------
// Error-context helpers
// ---------------------------------------------------------------------------

// The canonical debug-message operation returns an owned UTF-8 buffer through
// a pointer/length pair. Keep the return area single-instance, like the other
// small ABI result buffers in this runtime. Not re-entrancy safe: the result
// must be read before anything else can call `debugMessage`.
const __ERROR_CONTEXT_RET: usize = changetype<usize>(memory.data(16));

export class ErrorContext {
  constructor(public handle: i32) {}

  static new(debugMessage: string): ErrorContext {
    const encoded = String.UTF8.encode(debugMessage);
    const len = <usize>encoded.byteLength;
    const ptr = changetype<usize>(encoded);
    return new ErrorContext(__error_context_new_utf8(ptr, len));
  }

  debugMessage(): string {
    store<usize>(__ERROR_CONTEXT_RET, 0);
    store<usize>(__ERROR_CONTEXT_RET + sizeof<usize>(), 0);
    __error_context_debug_message_utf8(this.handle, __ERROR_CONTEXT_RET);
    const ptr = load<usize>(__ERROR_CONTEXT_RET);
    const len = load<usize>(__ERROR_CONTEXT_RET + sizeof<usize>());
    // Check the pointer before decoding: a zero pointer with a non-zero length
    // would otherwise read from address 0.
    if (ptr == 0) return "";
    const message = len == 0 ? "" : String.UTF8.decodeUnsafe(ptr, len);
    heap.free(ptr);
    return message;
  }

  drop(): void {
    __error_context_drop(this.handle);
  }
}

export function errorContextNew(debugMessage: string): i32 {
  return ErrorContext.new(debugMessage).handle;
}

export function errorContextDrop(handle: i32): void {
  __error_context_drop(handle);
}

export function errorContextDebugMessage(handle: i32): string {
  return new ErrorContext(handle).debugMessage();
}

// ---------------------------------------------------------------------------
// Explicit stackless task API
// ---------------------------------------------------------------------------

// Implementations own their state and decide how each canonical event advances
// it. Generated per-export task bases provide finish(), which records the
// result for delivery after resume() has unwound. Return CALLBACK_CODE_YIELD to
// yield, or callbackWait(set.handle) to wait. Task subclasses are unmanaged:
// persist only scalar handles and pointers, not managed strings, arrays, or
// class references. Lower managed values into owned buffers before yielding.
@unmanaged
export abstract class AsyncTask {
  resumeIndex: u32 = 0;
  abstract resume(event: i32, waitable: i32, code: i32): i32;
}

@unmanaged
export class UnimplementedTask extends AsyncTask {
  resume(_event: i32, _waitable: i32, _code: i32): i32 {
    unreachable();
    return CALLBACK_CODE_EXIT;
  }
}

// Async import subtasks are emitted per function by the generator as concrete
// `@unmanaged` classes owning their own status, handle, result area, and
// lowered parameters. A shared managed subtask class is deliberately absent:
// it could not be stored in an `@unmanaged` task across a yield.

// Tasks are unmanaged and recovered from the context-0 raw pointer via
// changetype. The callback ABI carries no task identity beyond this slot, so
// nested scheduler tasks in the same model task would be ambiguous.

// Set when the in-flight task is delivered EVENT_CANCEL, cleared when it
// completes. Only one task can occupy context-0 at a time.
let cancelRequested: bool = false;

export class Scheduler {
  @inline(false)
  static start<T extends AsyncTask>(task: T): i32 {
    if (contextGet() != 0) unreachable();
    const ptr = changetype<usize>(task);
    // Capture AS's concrete/virtual method thunk before retaining only a pointer.
    const resume = task.resume;
    task.resumeIndex = resume.index;
    contextSet(ptr);
    return task.resume(EVENT_NONE, 0, 0);
  }

  @inline(false)
  static resume(event: i32, waitable: i32, code: i32): i32 {
    const ptr = contextGet();
    // A callback delivered with no task in context-0 means the host and the
    // guest disagree about task identity; failing loudly beats losing the event.
    if (ptr == 0) unreachable();
    const task = changetype<AsyncTask>(ptr);
    // Bound AS methods take `this` before their declared arguments.
    if (event == EVENT_CANCEL) {
      // The task must observe the cancel so it can release its waitables, but
      // the canonical ABI requires the callback to return EXIT afterwards and
      // permits exactly one of task.return / task.cancel. Record the request
      // and let the generated finish helper issue whichever the task did not.
      cancelRequested = true;
      call_indirect<i32>(task.resumeIndex, ptr, event, waitable, code);
      return CALLBACK_CODE_EXIT;
    }
    return call_indirect<i32>(task.resumeIndex, ptr, event, waitable, code);
  }

  // True when the in-flight task was delivered EVENT_CANCEL. Safe as a single
  // global because `start` rejects a nested task while context-0 is occupied.
  static wasCancelled(): bool {
    return cancelRequested;
  }

  static current(): AsyncTask {
    const ptr = contextGet();
    assert(ptr != 0);
    return changetype<AsyncTask>(ptr);
  }

  static release(ptr: usize): void {
    if (ptr != 0) heap.free(ptr);
  }

  static complete(ptr: usize): void {
    if (contextGet() == ptr) {
      contextSet(0);
      cancelRequested = false;
    }
  }

  static yield(): i32 {
    return CALLBACK_CODE_YIELD;
  }

  // Convenience over `callbackWait` for code that already holds a
  // `WaitableSet`. Returning this is safe under the callback ABI; calling
  // `set.wait()` is not.
  static wait(set: WaitableSet): i32 {
    return callbackWait(set.handle);
  }
}
