// Generated by wit-bindgen. DO NOT EDIT.
//
// Async runtime support for wit-bindgen AssemblyScript bindings.
//
// AssemblyScript has no language-level async/await or event loop, so async
// component-model support is an explicit stackless runtime:
// generated export wrappers return callback codes to the host and the host
// drives the wasm `[callback]` export with waitable events.
//
// This file only declares the *shared* pieces: waitable-set wrappers, event
// constants, subtask helpers, and the packing/unpacking of canonical status
// codes. Per-function `task.return` helpers are emitted by the generator.
// Future/stream payload endpoint operations are deliberately not exposed yet.

// ---------------------------------------------------------------------------
// Canonical constants (mirrors the C/Rust/MoonBit runtimes)
// ---------------------------------------------------------------------------

// Subtask status codes returned by async imports.
export const STATUS_STARTING: i32 = 0;
export const STATUS_STARTED: i32 = 1;
export const STATUS_RETURNED: i32 = 2;
export const STATUS_STARTED_CANCELLED: i32 = 3;
export const STATUS_RETURNED_CANCELLED: i32 = 4;

// Waitable (future/stream) result codes.
export const WAITABLE_COMPLETED: i32 = 0;
export const WAITABLE_DROPPED: i32 = 1;
export const WAITABLE_CANCELLED: i32 = 2;

// Callback codes returned by async export wrappers.
export const CALLBACK_CODE_EXIT: i32 = 0;
export const CALLBACK_CODE_YIELD: i32 = 1;

// Event codes delivered to the `[callback]` export.
export const EVENT_NONE: i32 = 0;
export const EVENT_SUBTASK: i32 = 1;
export const EVENT_STREAM_READ: i32 = 2;
export const EVENT_STREAM_WRITE: i32 = 3;
export const EVENT_FUTURE_READ: i32 = 4;
export const EVENT_FUTURE_WRITE: i32 = 5;
export const EVENT_CANCEL: i32 = 6;

// Packing helpers.
//
// A callback code WAIT(set) is `2 | (set << 4)`.
// A subtask status is `state | (handle << 4)`.
// A waitable status is `state | (count << 4)`, or -1 while blocked.

@inline
export function callbackWait(set: i32): i32 {
  return 2 | (set << 4);
}

@inline
export function subtaskState(status: i32): i32 {
  return status & 0xf;
}

@inline
export function subtaskHandle(status: i32): i32 {
  return status >> 4;
}

@inline
export function waitableState(status: i32): i32 {
  return status & 0xf;
}

@inline
export function waitableCount(status: i32): i32 {
  return status >> 4;
}

// ---------------------------------------------------------------------------
// Canonical built-in imports shared by every async world.
// ---------------------------------------------------------------------------

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-new]")
declare function __waitable_set_new(): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-drop]")
declare function __waitable_set_drop(set: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-join]")
declare function __waitable_join(waitable: i32, set: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-poll]")
declare function __waitable_set_poll(set: i32, payload: usize): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[waitable-set-wait]")
declare function __waitable_set_wait(set: i32, payload: usize): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[subtask-cancel]")
declare function __subtask_cancel(handle: i32): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[subtask-drop]")
declare function __subtask_drop(handle: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[backpressure-inc]")
declare function __backpressure_inc(): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[backpressure-dec]")
declare function __backpressure_dec(): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("[export]$root", "[task-cancel]")
declare function __task_cancel(): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[context-set-0]")
declare function __context_set_0(value: usize): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[context-get-0]")
declare function __context_get_0(): usize;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[thread-yield]")
declare function __thread_yield(): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[error-context-new-utf8]")
declare function __error_context_new_utf8(ptr: usize, len: usize): i32;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[error-context-drop]")
declare function __error_context_drop(handle: i32): void;

// @ts-ignore: imported from the canonical ABI core module.
@external("$root", "[error-context-debug-message-utf8]")
declare function __error_context_debug_message_utf8(handle: i32, retptr: usize): void;

// ---------------------------------------------------------------------------
// Waitable-set wrapper
// ---------------------------------------------------------------------------

// Waitable event payload: [waitable, code]. Single-instance buffer; wait/poll
// results must be consumed before the next call.
const __WAITABLE_PAYLOAD: usize = changetype<usize>(memory.data(8));

export class WaitableSet {
  waitable: i32 = 0;
  code: i32 = 0;

  constructor(public handle: i32) {}

  static new(): WaitableSet {
    return new WaitableSet(__waitable_set_new());
  }

  join(waitable: i32): void {
    __waitable_join(waitable, this.handle);
  }

  wait(): i32 {
    store<i32>(__WAITABLE_PAYLOAD, 0);
    store<i32>(__WAITABLE_PAYLOAD + 4, 0);
    const event = __waitable_set_wait(this.handle, __WAITABLE_PAYLOAD);
    this.waitable = load<i32>(__WAITABLE_PAYLOAD);
    this.code = load<i32>(__WAITABLE_PAYLOAD + 4);
    return event;
  }

  poll(): i32 {
    store<i32>(__WAITABLE_PAYLOAD, 0);
    store<i32>(__WAITABLE_PAYLOAD + 4, 0);
    const event = __waitable_set_poll(this.handle, __WAITABLE_PAYLOAD);
    this.waitable = load<i32>(__WAITABLE_PAYLOAD);
    this.code = load<i32>(__WAITABLE_PAYLOAD + 4);
    return event;
  }

  drop(): void {
    __waitable_set_drop(this.handle);
  }
}

// ---------------------------------------------------------------------------
// Subtask / cancellation / context helpers
// ---------------------------------------------------------------------------

export function subtaskCancel(subtask: i32): i32 {
  return __subtask_cancel(subtask);
}

export function subtaskDrop(subtask: i32): void {
  __subtask_drop(subtask);
}

export function waitableJoin(waitable: i32, set: i32): void {
  __waitable_join(waitable, set);
}

export function waitableSetNew(): i32 {
  return __waitable_set_new();
}

export function waitableSetWait(set: i32, payload: usize): i32 {
  return __waitable_set_wait(set, payload);
}

export function waitableSetDrop(set: i32): void {
  __waitable_set_drop(set);
}

export function backpressureInc(): void {
  __backpressure_inc();
}

export function backpressureDec(): void {
  __backpressure_dec();
}

export function taskCancel(): void {
  __task_cancel();
}

// Per-task context slot (context-set/get-0). Generated export wrappers store
// task state here across wait/event boundaries, exactly like the C backend's
// `test_context_set_0`.
export function contextSet(value: usize): void {
  __context_set_0(value);
}

export function contextGet(): usize {
  return __context_get_0();
}

export function threadYield(): void {
  __thread_yield();
}

// ---------------------------------------------------------------------------
// Error-context helpers
// ---------------------------------------------------------------------------

// The canonical debug-message operation returns an owned UTF-8 buffer through
// a pointer/length pair. Keep the return area single-instance, like the other
// small ABI result buffers in this runtime.
const __ERROR_CONTEXT_RET: usize = changetype<usize>(memory.data(16));

export class ErrorContext {
  constructor(public handle: i32) {}

  static new(debugMessage: string): ErrorContext {
    const encoded = String.UTF8.encode(debugMessage);
    const len = <usize>encoded.byteLength;
    const ptr = changetype<usize>(encoded);
    return new ErrorContext(__error_context_new_utf8(ptr, len));
  }

  debugMessage(): string {
    store<usize>(__ERROR_CONTEXT_RET, 0);
    store<usize>(__ERROR_CONTEXT_RET + sizeof<usize>(), 0);
    __error_context_debug_message_utf8(this.handle, __ERROR_CONTEXT_RET);
    const ptr = load<usize>(__ERROR_CONTEXT_RET);
    const len = load<usize>(__ERROR_CONTEXT_RET + sizeof<usize>());
    const message = len == 0 ? "" : String.UTF8.decodeUnsafe(ptr, len);
    if (ptr != 0) heap.free(ptr);
    return message;
  }

  drop(): void {
    __error_context_drop(this.handle);
  }
}

export function errorContextNew(debugMessage: string): i32 {
  return ErrorContext.new(debugMessage).handle;
}

export function errorContextDrop(handle: i32): void {
  __error_context_drop(handle);
}

export function errorContextDebugMessage(handle: i32): string {
  return new ErrorContext(handle).debugMessage();
}

// ---------------------------------------------------------------------------
// Explicit stackless task API
// ---------------------------------------------------------------------------

// Implementations own their state and decide how each canonical event advances
// it. Generated per-export task bases provide finish(), which records the
// result for delivery after resume() has unwound. Return CALLBACK_CODE_YIELD to
// yield, or callbackWait(set.handle) to wait. Task subclasses are unmanaged:
// persist only scalar handles and pointers, not managed strings, arrays, or
// class references. Lower managed values into owned buffers before yielding.
@unmanaged
export abstract class AsyncTask {
  abstract resume(event: i32, waitable: i32, code: i32): i32;
}

@unmanaged
export class UnimplementedTask extends AsyncTask {
  resume(_event: i32, _waitable: i32, _code: i32): i32 {
    unreachable();
    return CALLBACK_CODE_EXIT;
  }
}

// An async import starts a canonical subtask. The result address remains valid
// until the caller has observed completion and lifted its result.
export class AsyncSubtask {
  status: i32 = 0;
  state: i32 = STATUS_STARTING;
  handle: i32 = 0;

  constructor(public result: usize) {}

  start(status: i32): void {
    this.status = status;
    this.state = subtaskState(status);
    this.handle = subtaskHandle(status);
  }

  join(set: WaitableSet): void {
    if (this.handle != 0) set.join(this.handle);
  }

  leave(): void {
    if (this.handle != 0) __waitable_join(this.handle, 0);
  }

  cancel(): i32 {
    return this.handle == 0 ? this.status : subtaskCancel(this.handle);
  }

  drop(): void {
    if (this.handle != 0) subtaskDrop(this.handle);
  }
}

// Tasks are unmanaged and recovered from the context-0 raw pointer via
// changetype. A single global task would resume the wrong state machine under
// reentrancy, so the current task always comes from the context slot.

export class Scheduler {
  @inline(false)
  static start(task: AsyncTask): i32 {
    const ptr = changetype<usize>(task);
    contextSet(ptr);
    return task.resume(EVENT_NONE, 0, 0);
  }

  @inline(false)
  static resume(event: i32, waitable: i32, code: i32): i32 {
    const ptr = contextGet();
    if (ptr == 0) return CALLBACK_CODE_EXIT;
    const task = changetype<AsyncTask>(ptr);
    if (event == EVENT_CANCEL) taskCancel();
    return task.resume(event, waitable, code);
  }

  static current(): AsyncTask {
    const ptr = contextGet();
    assert(ptr != 0);
    return changetype<AsyncTask>(ptr);
  }

  static release(ptr: usize): void {
    if (ptr != 0) heap.free(ptr);
  }

  static complete(ptr: usize): void {
    if (contextGet() == ptr) contextSet(0);
  }

  static yield(): i32 {
    return CALLBACK_CODE_YIELD;
  }

  static wait(set: WaitableSet): i32 {
    return callbackWait(set.handle);
  }
}
